In [9]:
import pandas as pd
import numpy as np

df = pd.read_excel(r"C:\Users\yashm\Desktop\AQI 2019-2023\Datasets\Air-Quality-dataset.xlsx")
df.head()

,State/Union Territory,City/town/village,Year,SO2 Annual Average,NO2 Annual Average,PM10 Annual Average,PM2.5 Annual Average
0,Andhra Pradesh,Amaravati,2021,14,12,55,28
1,Andhra Pradesh,Anatapur,2021,7,16,64,30
2,Andhra Pradesh,Chittor,2021,5,14,46,25
3,Andhra Pradesh,Eluru,2021,5,17,63,30
4,Andhra Pradesh,Guntur,2021,5,17,60,29

In [10]:
df = df.rename(columns={'SO2 Annual Average': 'SO2', 
                        'NO2 Annual Average': 'NO2',
                        'PM10 Annual Average': 'PM10',
                        'PM2.5 Annual Average': 'PM2.5'})
df.head()

  State/Union Territory City/town/village  Year SO2 NO2 PM10 PM2.5
0        Andhra Pradesh         Amaravati  2021  14  12   55    28
1        Andhra Pradesh          Anatapur  2021   7  16   64    30
2        Andhra Pradesh           Chittor  2021   5  14   46    25
3        Andhra Pradesh             Eluru  2021   5  17   63    30
4        Andhra Pradesh            Guntur  2021   5  17   60    29

In [11]:
df.columns = (
    df.columns.str.strip()
              .str.lower()
              .str.replace(" ", "_")
)
df.head()

  state/union_territory city/town/village  year so2 no2 pm10 pm2.5
0        Andhra Pradesh         Amaravati  2021  14  12   55    28
1        Andhra Pradesh          Anatapur  2021   7  16   64    30
2        Andhra Pradesh           Chittor  2021   5  14   46    25
3        Andhra Pradesh             Eluru  2021   5  17   63    30
4        Andhra Pradesh            Guntur  2021   5  17   60    29

In [12]:
df["year"] = df["year"].astype("int")
pollutants = ["so2","no2","pm10","pm2.5"]
df[pollutants] = df[pollutants].apply(pd.to_numeric, errors = "coerce")
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1252 entries, 0 to 1251
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   state/union_territory  1252 non-null   object
 1   city/town/village      1252 non-null   object
 2   year                   1252 non-null   int64
 3   so2                    1226 non-null   float64
 4   no2                    1231 non-null   float64
 5   pm10                   1235 non-null   float64
 6   pm2.5                  908 non-null    float64
dtypes: float64(4), int64(1), object(2)
memory usage: 68.6+ KB

state/union_territory      0
city/town/village          0
year                       0
so2                       26
no2                       21
pm10                      17
pm2.5                    344
dtype: int64

In [13]:
df = df.dropna(subset = ["so2","no2","pm10"])
df.isna().sum()

state/union_territory      0
city/town/village          0
year                       0
so2                        0
no2                        0
pm10                       0
pm2.5                    326
dtype: int64

In [14]:
df["pm2.5"] = df.groupby("state/union_territory")["pm2.5"].transform(lambda x: x.fillna(x.median()))
df.isna().sum()

state/union_territory    0
city/town/village        0
year                     0
so2                      0
no2                      0
pm10                     0
pm2.5                    0
dtype: int64

In [15]:
df["state/union_territory"] = df["state/union_territory"].str.strip()
df["city/town/village"] = df["city/town/village"].str.strip()

In [16]:
df.to_csv("clean_aqi_dataset.csv", index=False)